/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-07-20 00:32:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/css/style.css\">\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<div id=\"divItem\">\r\n");
      out.write("\t<span class=\"mitems\"><img src=\"/resources/img/logo.png\" align=middle ></span>\r\n");
      out.write("\t<div class=\"dropdown\">\r\n");
      out.write("\t\t<button class=\"dropbtn\">유기견</button>\r\n");
      out.write("\t\t<div class=\"dropdown-content\">\r\n");
      out.write("\t\t\t<a href=\"#\">입양절차</a> \r\n");
      out.write("\t\t\t<a href=\"#\">유기견 목록</a> \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"dropdown\">\r\n");
      out.write("\t\t<button class=\"dropbtn\">실종동물</button>\r\n");
      out.write("\t\t<div class=\"dropdown-content\">\r\n");
      out.write("\t\t\t<a href=\"#\">실종 신고</a> \r\n");
      out.write("\t\t\t<a href=\"#\">유기 제보</a> \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"dropdown\">\r\n");
      out.write("\t\t<button class=\"dropbtn\">접종예상비용</button>\r\n");
      out.write("\t\t<div class=\"dropdown-content\">\r\n");
      out.write("\t\t\t<a href=\"#\">예상 비용 확인</a> \r\n");
      out.write("\t\t\t<a href=\"#\">내 주변 병원 찾기</a> \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"dropdown\">\r\n");
      out.write("\t\t<button class=\"dropbtn\">커뮤니티</button>\r\n");
      out.write("\t\t<div class=\"dropdown-content\">\r\n");
      out.write("\t\t\t<a href=\"#\">자유게시판</a> \r\n");
      out.write("\t\t\t<a href=\"#\">후원금</a> \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<span class=\"itemSearch\"> \r\n");
      out.write("\t\t<input type=\"text\"\tplaceholder=\"     검색어를 입력하세요\"> &nbsp;&nbsp;&nbsp; \r\n");
      out.write("\t\t<input\ttype=\"button\" class=\"wordSearch\" value=\" SEARCH \">\r\n");
      out.write("\t</span>\r\n");
      out.write("\t<span class=\"items\"><a href=\"\">LOGIN</a></span>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
