/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-07-19 12:49:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class menu2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("@import url(\"http://fonts.googleapis.com/earlyaccess/nanumgothic.css\");\r\n");
      out.write("* { font-family:\"Nanum Gothic\" !important }\r\n");
      out.write("\t#divItem {\r\n");
      out.write("\t\twidth:1500px;\r\n");
      out.write("\t\tmargin-top:20px;\r\n");
      out.write("\t\tposition: fixed;\t\r\n");
      out.write("\t\ttop: 0;\r\n");
      out.write("\t\t/* width: 100% */\r\n");
      out.write("\t\tleft: 0;\r\n");
      out.write("\t\tright: 0;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#divItem img{\r\n");
      out.write("\t\twidth:130px;\r\n");
      out.write("\t\tmargin-left:115px;\r\n");
      out.write("\t\tcursor:pointer;\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.items {\r\n");
      out.write("\t\tmargin-left:50px;\r\n");
      out.write("\t\tfont-size: 20px;\r\n");
      out.write("\t\tfont-weight:bold;\r\n");
      out.write("\t\tcursor:pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.items a {\r\n");
      out.write("\t\ttext-decoration:none;\r\n");
      out.write("\t\tcolor:black;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.itemSearch {\r\n");
      out.write("\t\tmargin-left:40px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.itemSearch input[type='text'] {\r\n");
      out.write("\t   height: 37px; \r\n");
      out.write("\t   width:250px;\r\n");
      out.write("\t   background-color: #ebecee;\r\n");
      out.write("\t   border-radius: 30px 30px 30px 30px;\r\n");
      out.write("\t   border: none;\r\n");
      out.write("\t   outline: none;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.wordSearch {\r\n");
      out.write("\t\tbackground: #F2BB13;\r\n");
      out.write("\t\tborder-radius: 5px 5px 5px 5px;\r\n");
      out.write("\t\tcursor:pointer;\t\r\n");
      out.write("\t\tfont-weight:bold;\r\n");
      out.write("\t\theight:35px;\r\n");
      out.write("\t\tborder: none;\r\n");
      out.write("\t\toutline: none;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<div id=\"divItem\">\r\n");
      out.write("\t<span class=\"mitems\"><img src=\"/resources/img/logo.png\" align=middle ></span>\r\n");
      out.write("\t<span class=\"items\"><a href=\"\">유기견</a>\r\n");
      out.write("\t\t<a href=\"#\">입양 절차</a>\r\n");
      out.write("\t\t<a href=\"#\">유기견 목록</a>\r\n");
      out.write("\t</span>\r\n");
      out.write("\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|\r\n");
      out.write("\t<span class=\"items\"><a href=\"\">실종동물</a>\r\n");
      out.write("\t\t<a href=\"#\">유기 신고</a>\r\n");
      out.write("\t\t<a href=\"#\">유기 제보</a>\r\n");
      out.write("\t</span>\r\n");
      out.write("\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|\r\n");
      out.write("\t<span class=\"items\"><a href=\"\">접종예상비용</a>\r\n");
      out.write("\t\t<a href=\"#\">예상 비용 체크</a>\r\n");
      out.write("\t\t<a href=\"#\">내 주변 병원 찾기</a>\r\n");
      out.write("\t</span>\r\n");
      out.write("\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|\r\n");
      out.write("\t<span class=\"items\"><a href=\"\">커뮤니티</a>\r\n");
      out.write("\t\t<a href=\"#\">자유게시판</a>\r\n");
      out.write("\t\t<a href=\"#\">후원하기</a>\r\n");
      out.write("\t</span>\r\n");
      out.write("\t<span class=\"itemSearch\">\r\n");
      out.write("\t\t<input type=\"text\" placeholder=\"     검색어를 입력하세요\">\r\n");
      out.write("\t\t&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t<input type=\"button\" class=\"wordSearch\" value=\"SEARCH\">\r\n");
      out.write("\t</span>\r\n");
      out.write("\t<span class=\"items\"><a href=\"\">LOGIN</a></span>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
